#!/usr/bin/env bash

PAGE=${1:-Walrus}

SECTIONS=$(curl -s "https://en.wikipedia.org/w/api.php?action=parse&page=$PAGE&format=json&prop=sections")

# first sentence
print_fst_sen() {
    local fst_sen=$(curl -s "https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=$PAGE&format=json&exintro&explaintext&exsentences=1" | jq -r '.query.pages | to_entries | .[0].value.extract')

    printf "%s\n" "$fst_sen"
}

print_sections() {
    # get section name list
    mapfile -t section_names < <(jq -r '.parse.sections[].line' <<< $SECTIONS)

    printf "sections:\n"

    for section in "${section_names[@]}"; do
        printf '%s %s\n' '-' "$section"
    done
}

print_fst_sen
printf "\n" ""
print_sections
